### ISSUE TITLE
Support uploads bigger than 51200 bytes

### ISSUE THREAD

**Issue by bittrance** [burtcorp/cuffsert#12]
Currently, CuffSert supports URLs, but does not do automatic uploads for templates that are bigger than 51200 bytes. This is straight-forward except for the corner-case where we want to create a new stack from a big template and we don't know the S3 bucket name to upload to.

**Comment by iconara** [comment]
We have exactly the same problem in Regentanz (see https://github.com/burtcorp/regentanz/blob/a12e962891248904556bbcf670f976c517fe1bdc/lib/regentanz/template_compiler.rb#L62 where we hard coded a bucket name back when, and I forgot to remove when I prepared it for open source), but it feels like the name of the bucket is deterministic (we have three, for three different regions, and they all have the same letter combination).
