### ISSUE TITLE
Without -m to run with stack's existing parameters

### ISSUE THREAD

**Issue by bittrance** [burtcorp/cuffsert#8]
Use case: I want to change a stack, but don't really care about parameters, as I expect them not to have changed. Currently, I would need to do `cuffdown` and then `cuffsert`, but the latter should be able to fetch the parameters implicitly. This is a typical ops use case and is different from the dev use cases that Cuffsert currently support.

Proposed solution: If the user does `cuffsert --name 'production-foo' ze-template.json` (i.e. excluding `-m metadata.yml`) and the stack exists we could read the existing parameters and use them for the update, preferably saying that the value should not change. In this case, we should validate that the list of parameters between the stack and the template has not changed. If `--parameter` is passed on command line, those parameters should still be changed. In this case using `--selector` or `--name` is interchangeable.

If we have at least one `-v`, we should list current value of all parameters, and highlight any that change due to `--parameter`.

We should refuse to run with `--replace` for now. (It could be supported, but have problems with e.g. password fields.)

**Comment by iconara** [comment]
This would be a great feature. I've wanted it a couple of times. I've got my own stash of parameter files, but when someone else makes a change they get stale and I can't even use cuffsert to update after a template change anymore (without going through all parameter values). With this feature I could.

**Comment by bittrance** [comment]
This is addressed in release 0.10.0.
